export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const CHANGE_ACCOUNT_STATUS = "CHANGE_ACCOUNT_STATUS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHECK_PASSWORD = "CHECK_PASSWORD";
export const CREATE_ADMIN_ACCOUNT = "CREATE_ADMIN_ACCOUNT";

export const GET_ACTIVITY_LOG_LIST = "GET_ACTIVITY_LOG_LIST";

export const GET_ATTENDANCE_LOG_LIST = "GET_ATTENDANCE_LOG_LIST";
