export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_PRODUCT_STATUS = "CHANGE_PRODUCT_STATUS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const PRODUCT_LOADING = "PRODUCT_LOADING";

export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const GET_VOUCHER_LIST = "GET_VOUCHER_LIST";
export const ADD_VOUCHER = "ADD_VOUCHER";
export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const CHANGE_VOUCHER_STATUS = "CHANGE_VOUCHER_STATUS";

export const ADD_REVIEW = "ADD_REVIEW";
export const GET_REVIEW_LIST = "GET_REVIEW_LIST";

export const UPDATE_PRODUCT_VARIATION = "UPDATE_PRODUCT_VARIATION";
export const ADD_PRODUCT_VARIATION = "ADD_PRODUCT_VARIATION";
