export const GET_TRANSACTION_LIST = "GET_TRANSACTION_LIST";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const CHANGE_TRANSACTION_STATUS = "CHANGE_TRANSACTION_STATUS";

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const GET_TRANSACTION_ITEM_LIST = "GET_TRANSACTION_ITEM_LIST";
export const ADD_TRANSACTION_ITEMS = "ADD_TRANSACTION_ITEMS";
export const UPDATE_TRANSACTION_STATUS = "UPDATE_TRANSACTION_STATUS";
export const UPDATE_TRANSACTION_ITEMS = "UPDATE_TRANSACTION_ITEMS";

export const ADD_REFUND = "ADD_REFUND";
export const GET_REFUND_LIST = "GET_REFUND_LIST";
export const UPDATE_REFUND = "UPDATE_REFUND";
